create table sc_user
(
	id BIGINT generated by default as identity
		constraint pk_sc_user
			primary key,
	user_name VARCHAR(255),
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	e_mail VARCHAR(255)
		constraint uc_sc_user_e_mail
			unique
);

