create table sc_user
(
    id BIGINT generated by default as identity
        constraint pk_sc_user
            primary key,
    user_name VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    e_mail VARCHAR(255)
        constraint uc_sc_user_e_mail
            unique
);



create table sc_schedule
(
    id BIGINT generated by default as identity
        constraint pk_sc_schedule
            primary key,
    description VARCHAR(255),
    end_date TIMESTAMP WITHOUT TIME ZONE not null,
    group_id VARCHAR(255),
    is_editable BOOLEAN,
    schedule_id VARCHAR(255),
    start_date TIMESTAMP WITHOUT TIME ZONE not null,
    style_class VARCHAR(255),
    title VARCHAR(255),
    url VARCHAR(255),
    user_entity_id BIGINT
        constraint FK_SC_SCHEDULE_ON_USERENTITY
            references sc_user
);


